version: "3"

services:
  ssis-app-api:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/

    ports:
      - "4000:4000"

    env_file:
      - .env

    environment:
      - MONGO_URL_DEV=mongodb://mongo/ssis-app-api-dev
      - MONGO_URL_PROD=mongodb://mongo/ssis-app-api-prod
      - NODE_ENV=development

    depends_on:
      - mongo
      - redis

  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: "redis"
    restart: always
    ports:
      - "6379:6379"
