/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file realtid.js
 * @author: Oskar Yildiz <oskar> 2018-04-22T10:25:42+02:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-04-22T10:25:42+02:00.
 * Last modified by oskar on 2018-04-22T10:25:42+02:00
 *
 */

import request from 'superagent';

import constants from '../config/constants';

/**
 * @function getDepartures
 *
 * @description
 * CLARIFY: Should get the SL departures for a specific site
 *
 * @param   {Number} siteId     The bus stop id
 * @param   {Number} timeWindow Time in minutes (max: 60)
 * @param   {String} format     The response format (json|xml)
 *
 * @returns {Object}            The departures   
 */
export async function getDepartures({ siteId, timeWindow, format }) {
  try {
    let { res: { text } } = await request.get(
      `http://api.sl.se/api2/realtimedeparturesV4.${format}?key=${constants.SL_REALTID_API_KEY}&siteid=${siteId}&timewindow=${timeWindow}`,
    );
    text = JSON.parse(text);
    const departures = text;
    return departures;
  } catch (err) {
    throw err;
  }
}
