/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file schedule.js
 * @author: Oskar Yildiz <oskar> 2018-02-22T21:35:29+01:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-02-22T21:35:29+01:00.
 * Last modified by oskar on 2018-02-22T21:35:29+01:00
 *
 */

import request from 'superagent';

export async function getFullScheduleForClass(userClass) {
  try {
    let { res: { text } } = await request.get(
      `https://api.ssis.nu/cal/?room=${userClass}`,
    );
    text = JSON.parse(text);
    const schedule = text;
    return schedule;
  } catch (err) {
    throw err;
  }
}
