/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file email.js
 * @author: Oskar Yildiz <oskar> 2018-02-16T14:52:11+01:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-02-16T14:52:11+01:00.
 * Last modified by oskar on 2018-02-16T14:52:11+01:00
 *
 */

/**
 * @function formatSSISEmail
 *
 * @description: Returns email for the user
 *
 * DOING: Returns a string with the school formatted email created from the username in the arguments.
 * @param   {String} username
 *
 * @returns {String} email Returns the proper stockholmscience email address.
 */
const formatSSISEmail = username => `${username}@stockholmscience.se`;

export default formatSSISEmail;
